[package]
name = "crabfleet-viewer"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
publish.workspace = true

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
crabfleet-client-core.workspace = true
crabfleet-cloud = { path = "../cloud" }
crabfleet-fluid = { path = "../fluid" }
crabfleet-rtc = { path = "../rtc" }
zeroize = "1.9.0"
eframe = { version = "0.36.2", default-features = false, features = [
  "default_fonts",
  "wgpu",
  "x11",
  "wayland",
  "accesskit",
] }
url = "2.5.8"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
tungstenite.workspace = true
png = "0.18.1"

[target.'cfg(not(target_arch = "wasm32"))'.dev-dependencies]
crabfleet-demo-server = { path = "../demo-server" }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen = "0.2.128"
wasm-bindgen-futures = "0.4.78"
js-sys = "0.3.105"
web-sys = { version = "0.3.105", features = [
  "Window",
  "Document",
  "Location",
  "HtmlCanvasElement",
  "WebSocket",
  "BinaryType",
  "MessageEvent",
  "Event",
  "CloseEvent",
] }
wgpu = { version = "30.0.1", default-features = false, features = ["webgpu", "webgl", "wgsl"] }
