export type RuntimeEnv = {
  DB: D1Database;
  DESKTOP_RELAY?: DurableObjectNamespace;
  CRABBOX_BOOTSTRAP_TOKEN?: string;
  GITHUB_CLIENT_ID?: string;
  GITHUB_CLIENT_SECRET?: string;
  GITHUB_REDIRECT_URI?: string;
  GITHUB_ORG?: string;
  CRABBOX_TOKEN_ENCRYPTION_KEY?: string;
  CRABFLEET_LABEL?: string;
  CRABFLEET_CANONICAL_URL?: string;
  CRABFLEET_PRODUCT_URL?: string;
  CRABFLEET_DEV_LOGIN_ENABLED?: string;
  CRABFLEET_TRUSTED_PROXY_AUTO_ROLE?: string;
  CRABFLEET_TRUSTED_PROXY_ORIGIN?: string;
  CRABFLEET_TRUSTED_PROXY_PUBLIC_ORIGIN?: string;
  CRABFLEET_TRUSTED_USER_HEADER?: string;
  CRABFLEET_TRUSTED_PROXY_SECRET?: string;
};
