import { execFile } from "node:child_process";
import { mkdir, readFile, rm, writeFile } from "node:fs/promises";
import { promisify } from "node:util";

import { GHOSTTY_ASSET_PATHS, readGhosttyAsset } from "@openclaw/libterminal/node";

import { css, js, preThemeScript, themeToggleHtml } from "./docs-site-assets.mjs";
import { escapeHtml, markdownToHtml } from "./worker-markdown.mjs";

const run = promisify(execFile);
const appBuildRoot = new URL("../dist/app-bundle/", import.meta.url);
const appPath = new URL("../dist/app-bundle/app.html", import.meta.url);
const specPath = new URL("../docs/spec.md", import.meta.url);
const specV2Path = new URL("../docs/spec-v2.md", import.meta.url);
const logoPath = new URL("../src/assets/crabbox-logo.png", import.meta.url);
const ogImagePath = new URL("../src/assets/crabfleet-og.png", import.meta.url);
const lucideIconNodesPath = new URL(
	"../node_modules/lucide-static/icon-nodes.json",
	import.meta.url,
);
const generatedPath = new URL("../src/generated.ts", import.meta.url);
const distRoot = new URL("../dist/", import.meta.url);
const distApp = new URL("../dist/app/", import.meta.url);
const distDocs = new URL("../dist/docs/", import.meta.url);
const appOrigin = "https://crabfleet.openclaw.ai";

await run(process.execPath, [
	new URL("../node_modules/vite/bin/vite.js", import.meta.url).pathname,
	"build",
	"--config",
	new URL("../vite.config.mjs", import.meta.url).pathname,
]);

const [
	appHtmlSource,
	rawSpecMarkdown,
	rawSpecV2Markdown,
	logoBytes,
	ogImageBytes,
	ghosttyWebJs,
	ghosttyWasmBytes,
	ghosttyExternalJs,
	lucideIconJson,
] = await Promise.all([
	readAppHtml(),
	readFile(specPath, "utf8"),
	readFile(specV2Path, "utf8"),
	readFile(logoPath),
	readFile(ogImagePath),
	requiredGhosttyAsset(GHOSTTY_ASSET_PATHS.module, "utf8"),
	requiredGhosttyAsset(GHOSTTY_ASSET_PATHS.wasm),
	requiredGhosttyAsset(GHOSTTY_ASSET_PATHS.browserExternal, "utf8"),
	readFile(lucideIconNodesPath, "utf8"),
]);

const logoDataUrl = `data:image/png;base64,${logoBytes.toString("base64")}`;
const logoBase64 = logoBytes.toString("base64");
const ogImageBase64 = ogImageBytes.toString("base64");
const ghosttyWasmBase64 = Buffer.from(ghosttyWasmBytes).toString("base64");
const ghosttyWasmAssetPath = GHOSTTY_ASSET_PATHS.wasm;
const lucideIconScript = buildLucideIconScript(JSON.parse(lucideIconJson));
const appHtml = (await inlineViteAssets(appHtmlSource))
	.replaceAll("__CRABBOX_LOGO__", logoDataUrl)
	.replaceAll("__GHOSTTY_WASM_PATH__", ghosttyWasmAssetPath)
	.replace("__LUCIDE_ICONS__", lucideIconScript);
const specMarkdown = stripFrontmatter(rawSpecMarkdown);
const specV2Markdown = stripFrontmatter(rawSpecV2Markdown);
const specHtml = renderSpecPage(specMarkdown, {
	activePath: "/docs/spec",
	markdownPath: "/docs/spec.md",
	title: "Crabfleet Spec",
});
const specV2Html = renderSpecPage(specV2Markdown, {
	activePath: "/docs/spec-v2",
	markdownPath: "/docs/spec-v2.md",
	title: "Crabfleet Spec v2",
});

await mkdir(new URL("../src/", import.meta.url), { recursive: true });
await writeFile(
	generatedPath,
	`// Generated by scripts/generate-assets.mjs. Do not edit by hand.\nexport const APP_HTML = ${JSON.stringify(appHtml)} as const;\nexport const LOGO_PNG_BASE64 = ${JSON.stringify(logoBase64)} as const;\nexport const OG_IMAGE_PNG_BASE64 = ${JSON.stringify(ogImageBase64)} as const;\nexport const SPEC_MARKDOWN = ${JSON.stringify(specMarkdown)} as const;\nexport const SPEC_HTML = ${JSON.stringify(specHtml)} as const;\nexport const SPEC_V2_MARKDOWN = ${JSON.stringify(specV2Markdown)} as const;\nexport const SPEC_V2_HTML = ${JSON.stringify(specV2Html)} as const;\nexport const GHOSTTY_WEB_JS = ${JSON.stringify(ghosttyWebJs)} as const;\nexport const GHOSTTY_WEB_PATH = ${JSON.stringify(GHOSTTY_ASSET_PATHS.module)} as const;\nexport const GHOSTTY_VT_WASM_BASE64 = ${JSON.stringify(ghosttyWasmBase64)} as const;\nexport const GHOSTTY_VT_WASM_PATH = ${JSON.stringify(ghosttyWasmAssetPath)} as const;\nexport const GHOSTTY_BROWSER_EXTERNAL_JS = ${JSON.stringify(ghosttyExternalJs)} as const;\nexport const GHOSTTY_BROWSER_EXTERNAL_PATH = ${JSON.stringify(GHOSTTY_ASSET_PATHS.browserExternal)} as const;\n`,
);

if (process.argv.includes("--static")) {
	await rm(distRoot, { recursive: true, force: true });
	await Promise.all([mkdir(distApp, { recursive: true }), mkdir(distDocs, { recursive: true })]);
	await writeFile(new URL("../dist/_redirects", import.meta.url), `/* ${appOrigin}/:splat 302\n`);
	await writeFile(new URL("../dist/index.html", import.meta.url), redirectHtml("/"));
	await writeFile(new URL("../dist/app/index.html", import.meta.url), redirectHtml("/app/"));
	await writeFile(new URL("../dist/docs/spec.md", import.meta.url), specMarkdown);
	await writeFile(new URL("../dist/docs/spec-v2.md", import.meta.url), specV2Markdown);
	await writeFile(new URL("../dist/crabbox-logo.png", import.meta.url), logoBytes);
	await writeFile(new URL("../dist/crabfleet-og.png", import.meta.url), ogImageBytes);
	await writeFile(new URL("../dist/healthz", import.meta.url), "ok\n");
}

function redirectHtml(path) {
	const target = `${appOrigin}${path}`;
	return `<!doctype html><meta charset="utf-8"><meta http-equiv="refresh" content="0; url=${target}"><title>Crabfleet</title><a href="${target}">Crabfleet</a>`;
}

async function requiredGhosttyAsset(pathname, encoding) {
	const asset = await readGhosttyAsset(pathname);
	if (!asset) throw new Error(`Missing Ghostty asset ${pathname}`);
	return encoding ? Buffer.from(asset.body).toString(encoding) : asset.body;
}

async function readAppHtml() {
	for (const candidate of [
		appPath,
		new URL("../dist/app-bundle/index.html", import.meta.url),
		new URL("../dist/app-bundle/src/app.html", import.meta.url),
	]) {
		try {
			return await readFile(candidate, "utf8");
		} catch {}
	}
	throw new Error("Vite app HTML was not generated");
}

async function inlineViteAssets(html) {
	let result = html;
	const scriptPattern = /<script type="module"(?: crossorigin)? src="([^"]+)"><\/script>/g;
	for (const match of html.matchAll(scriptPattern)) {
		const [tag, src] = match;
		const js = await readFile(viteAssetUrl(src), "utf8");
		result = result.replace(tag, `<script type="module">\n${js}\n</script>`);
	}
	const stylePattern = /<link rel="stylesheet"(?: crossorigin)? href="([^"]+)">/g;
	for (const match of html.matchAll(stylePattern)) {
		const [tag, href] = match;
		const css = await readFile(viteAssetUrl(href), "utf8");
		result = result.replace(tag, `<style>\n${css}\n</style>`);
	}
	return result;
}

function viteAssetUrl(path) {
	const relative = path.replace(/^\/?/, "");
	return new URL(relative, appBuildRoot);
}

function buildLucideIconScript(iconNodes) {
	const names = [
		"book-open",
		"check",
		"copy",
		"git-pull-request",
		"layout-grid",
		"link-2",
		"moon",
		"settings",
		"square-terminal",
		"sun",
		"terminal",
		"triangle-alert",
		"x",
	];
	const selected = Object.fromEntries(names.map((name) => [name, iconNodes[name]]));
	return `(() => {
  globalThis.lucideIconNodes = ${JSON.stringify(selected)};
})();`;
}

function stripFrontmatter(markdown) {
	return markdown.replace(/^---\n[\s\S]*?\n---\n+/, "");
}

function renderSpecPage(markdown, options = {}) {
	const title = options.title ?? "Crabfleet Spec";
	const activePath = options.activePath ?? "/docs/spec";
	const markdownPath = options.markdownPath ?? "/docs/spec.md";
	return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>${escapeHtml(title)}</title>
  <link rel="icon" type="image/png" href="/crabbox-logo.png">
  <script>${preThemeScript()}</script>
  <style>${css()}</style>
</head>
<body>
  <button class="nav-toggle" type="button" aria-label="Toggle navigation" aria-expanded="false">
    <span aria-hidden="true"></span><span aria-hidden="true"></span><span aria-hidden="true"></span>
  </button>
  <div class="shell">
    <aside class="sidebar">
      <div class="sidebar-head">
        <a class="brand" href="/docs/" aria-label="Crabfleet docs home">
          <img class="mark" src="/crabbox-logo.png" alt="" width="28" height="28">
          <span><strong>Crabfleet</strong><small>Control plane docs</small></span>
        </a>
        ${themeToggleHtml()}
      </div>
      <label class="search"><span>Search</span><input id="doc-search" type="search" placeholder="cards, runs, admin"></label>
      <nav>
        <section><h2>Start</h2><a class="nav-link" href="https://docs.crabfleet.ai/">Overview</a><a class="nav-link" href="https://docs.crabfleet.ai/quickstart/">Quickstart</a><a class="nav-link" href="https://docs.crabfleet.ai/architecture/">Architecture</a></section>
        <section><h2>Features</h2><a class="nav-link" href="https://docs.crabfleet.ai/cards/">Cards</a><a class="nav-link" href="https://docs.crabfleet.ai/runs/">Runs</a><a class="nav-link" href="https://docs.crabfleet.ai/github-actions-sessions/">GitHub Actions</a><a class="nav-link" href="https://docs.crabfleet.ai/macos-native-client/">macOS client</a><a class="nav-link" href="https://docs.crabfleet.ai/admin/">Admin</a></section>
        <section><h2>Reference</h2><a class="nav-link${markdownPath === "/docs/spec.md" ? " active" : ""}" href="/docs/spec.md">Spec markdown</a><a class="nav-link${activePath === "/docs/spec" ? " active" : ""}" href="/docs/spec">Spec</a><a class="nav-link${markdownPath === "/docs/spec-v2.md" ? " active" : ""}" href="/docs/spec-v2.md">Fleet v2 record markdown</a><a class="nav-link${activePath === "/docs/spec-v2" ? " active" : ""}" href="/docs/spec-v2">Fleet v2 record</a><a class="nav-link" href="https://docs.crabfleet.ai/api/">API reference</a><a class="nav-link" href="https://github.com/openclaw/crabfleet">GitHub</a><a class="nav-link" href="/app/">App</a></section>
      </nav>
    </aside>
    <main>
      <header class="hero">
        <div class="hero-text">
          <p class="eyebrow">Reference</p>
          <h1>${escapeHtml(title)}</h1>
        </div>
        <div class="hero-meta">
          <a class="repo" href="/">App</a>
          <a class="edit" href="${markdownPath}">Markdown</a>
        </div>
      </header>
      <div class="doc-grid">
        <article class="doc">${markdownToHtml(markdown)}</article>
        <nav class="toc" aria-label="Docs links"><h2>Docs</h2><a href="https://docs.crabfleet.ai/">Generated docs site</a><a href="https://docs.crabfleet.ai/api/">API reference</a></nav>
      </div>
    </main>
  </div>
  <script>${js()}</script>
</body>
</html>`;
}
