import { execFile } from "node:child_process";
import { mkdir, readFile, readdir, writeFile } from "node:fs/promises";
import { fileURLToPath } from "node:url";
import { promisify } from "node:util";

const appBuildRoot = new URL("../dist/app-bundle/", import.meta.url);
const inlinedAssets = new Set();
const appPath = new URL("../dist/app-bundle/app.html", import.meta.url);
await promisify(execFile)(process.execPath, [
  fileURLToPath(new URL("../node_modules/vite/bin/vite.js", import.meta.url)),
  "build",
  "--config",
  fileURLToPath(new URL("../vite.config.mjs", import.meta.url)),
]);
const appHtml = await inlineViteAssets(await readAppHtml());
const browserAssets = {};
for (const filename of await readdir(new URL("assets/", appBuildRoot))) {
  const assetPath = `/assets/${filename}`;
  if (inlinedAssets.has(assetPath)) continue;
  const bytes = await readFile(new URL(`assets/${filename}`, appBuildRoot));
  browserAssets[assetPath] = {
    base64: bytes.toString("base64"),
    contentType: filename.endsWith(".js")
      ? "text/javascript; charset=utf-8"
      : "application/octet-stream",
  };
}
const logo = await readFile(new URL("../src/assets/crabbox-logo.png", import.meta.url));
await mkdir(new URL("../src/", import.meta.url), { recursive: true });
await writeFile(
  new URL("../src/generated.ts", import.meta.url),
  `// Generated by scripts/generate-assets.mjs. Do not edit by hand.\nexport const APP_HTML = ${JSON.stringify(appHtml)} as const;\nexport const LOGO_PNG_BASE64 = ${JSON.stringify(logo.toString("base64"))} as const;\nexport const BROWSER_ASSETS: Record<string, { base64: string; contentType: string }> = ${JSON.stringify(browserAssets)};\n`,
);

async function readAppHtml() {
  for (const candidate of [
    appPath,
    new URL("../dist/app-bundle/index.html", import.meta.url),
    new URL("../dist/app-bundle/src/app.html", import.meta.url),
  ]) {
    try {
      return await readFile(candidate, "utf8");
    } catch {}
  }
  throw new Error("Vite app HTML was not generated");
}

async function inlineViteAssets(html) {
  let result = html;
  const scriptPattern = /<script type="module"(?: crossorigin)? src="([^"]+)"><\/script>/g;
  for (const match of html.matchAll(scriptPattern)) {
    const [tag, src] = match;
    inlinedAssets.add(src);
    const js = await readFile(viteAssetUrl(src), "utf8");
    result = result.replace(tag, `<script type="module">\n${js}\n</script>`);
  }
  const stylePattern = /<link rel="stylesheet"(?: crossorigin)? href="([^"]+)">/g;
  for (const match of html.matchAll(stylePattern)) {
    const [tag, href] = match;
    inlinedAssets.add(href);
    const css = await readFile(viteAssetUrl(href), "utf8");
    result = result.replace(tag, `<style>\n${css}\n</style>`);
  }
  return result;
}

function viteAssetUrl(path) {
  const relative = path.replace(/^\/?/, "");
  return new URL(relative, appBuildRoot);
}
